"""Seed data for the AETHERMOOR item catalogue."""

SEED_ITEMS: list[dict] = [
    {
        "id": "basic_sword",
        "name": "Basic Sword",
        "type": "weapon",
        "rarity": "common",
        "stackable": False,
        "max_stack": 1,
        "stats": {"bonus_attack": 3},
        "description": "A plain iron sword. Nothing fancy.",
        "equippable_slot": "main_hand",
    },
    {
        "id": "leather_armour",
        "name": "Leather Armour",
        "type": "armour",
        "rarity": "common",
        "stackable": False,
        "max_stack": 1,
        "stats": {"bonus_defense": 2},
        "description": "Supple leather armour offering modest protection.",
        "equippable_slot": "chest",
    },
    {
        "id": "iron_shield",
        "name": "Iron Shield",
        "type": "armour",
        "rarity": "common",
        "stackable": False,
        "max_stack": 1,
        "stats": {"bonus_defense": 1},
        "description": "A sturdy iron shield.",
        "equippable_slot": "off_hand",
    },
    {
        "id": "leather_cap",
        "name": "Leather Cap",
        "type": "armour",
        "rarity": "common",
        "stackable": False,
        "max_stack": 1,
        "stats": {"bonus_defense": 1},
        "description": "A simple leather cap.",
        "equippable_slot": "head",
    },
    {
        "id": "health_potion",
        "name": "Health Potion",
        "type": "consumable",
        "rarity": "common",
        "stackable": True,
        "max_stack": 20,
        "stats": {"hp_restore": 30},
        "description": "Restores 30 HP when consumed.",
        "equippable_slot": None,
    },
    {
        "id": "iron_ore",
        "name": "Iron Ore",
        "type": "material",
        "rarity": "common",
        "stackable": True,
        "max_stack": 99,
        "stats": {},
        "description": "Raw iron ore, used in smithing.",
        "equippable_slot": None,
    },
    {
        "id": "leather_strips",
        "name": "Leather Strips",
        "type": "material",
        "rarity": "common",
        "stackable": True,
        "max_stack": 99,
        "stats": {},
        "description": "Strips of cured leather for crafting.",
        "equippable_slot": None,
    },
    {
        "id": "healing_herbs",
        "name": "Healing Herbs",
        "type": "material",
        "rarity": "common",
        "stackable": True,
        "max_stack": 50,
        "stats": {},
        "description": "Fragrant herbs used in potion making.",
        "equippable_slot": None,
    },
    {
        "id": "silver_ring",
        "name": "Silver Ring",
        "type": "misc",
        "rarity": "uncommon",
        "stackable": False,
        "max_stack": 1,
        "stats": {"bonus_attack": 1},
        "description": "A simple silver ring with a faint magical resonance.",
        "equippable_slot": "ring_1",
    },
    {
        "id": "amulet_of_vitality",
        "name": "Amulet of Vitality",
        "type": "misc",
        "rarity": "uncommon",
        "stackable": False,
        "max_stack": 1,
        "stats": {"bonus_hp": 20},
        "description": "An amulet that bolsters the wearer's constitution.",
        "equippable_slot": "amulet",
    },
]
