# Homepage dashboard config for public services
services:
  - name: frontend
    url: http://dev-1.tail5b8dbe.ts.net:3000
  - name: gateway
    url: http://dev-1.tail5b8dbe.ts.net:8000
  - name: grafana
    url: http://dev-1.tail5b8dbe.ts.net:${GRAFANA_PORT:-5007}
  - name: prometheus
    url: http://dev-1.tail5b8dbe.ts.net:9090
  - name: loki
    url: http://dev-1.tail5b8dbe.ts.net:${LOKI_PORT:-3110}
  - name: cadvisor
    url: http://dev-1.tail5b8dbe.ts.net:8080
  - name: auth server
    url: http://dev-1.tail5b8dbe.ts.net:9000/docs
  - name: guild server
    url: http://dev-1.tail5b8dbe.ts.net:8014/docs
  - name: crafting server
    url: http://dev-1.tail5b8dbe.ts.net:8013/docs