---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  
title: Dev Homepage
    
background: 
  image: https://images.pexels.com/photos/1624496/pexels-photo-1624496.jpeg
  opacity: 30 # 0-100
